services:
  asterank:
    build: .
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://mongo"
      REDIS_HOST: "redis"
    ports:
      - 45135:80
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    command: --quiet --logpath /dev/null
    expose:
      - 27017
    volumes:
      - ./mongo_data:/data/db:rw

  redis:
    image: redis:latest
    expose:
      - 6379
